//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iakademi8_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Categories
    {
        public int categoryID { get; set; }
        public string categoryname { get; set; }
        public Nullable<int> parentID { get; set; }
        public string shortname { get; set; }
        public Nullable<bool> aktif { get; set; }
    }
}
