//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iakademi8_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_arama
    {
        public int KATEGORI { get; set; }
        public int URUN { get; set; }
        public int MARKA { get; set; }
        public string ARAMAISMI { get; set; }
    }
}
