//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iakademi8_proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WV_aktifurunler
    {
        public string productname { get; set; }
        public int productID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> onecikanlar { get; set; }
        public Nullable<int> coksatanlar { get; set; }
        public Nullable<long> stock { get; set; }
        public string notes { get; set; }
        public string bunabakanlar_bunadabakti { get; set; }
        public Nullable<int> kdv { get; set; }
        public string urunkodu { get; set; }
        public string keywords { get; set; }
        public string durumu { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string photopath { get; set; }
        public Nullable<int> supplierID { get; set; }
        public string categoryname { get; set; }
        public string shortname { get; set; }
        public string brandname { get; set; }
    }
}
